# Generated by Django 4.2.16 on 2024-11-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_name", models.CharField(max_length=255)),
                ("emp_img", models.ImageField(upload_to="images/")),
                ("emp_email", models.EmailField(max_length=50, unique=True)),
                ("emp_add", models.CharField(max_length=255)),
                ("emp_dept", models.CharField(max_length=10)),
            ],
        ),
    ]
